title: "Rita Altieri e Carlo Santarcangelo"
description: "In loving memory"
url: "https://lordgrilo.github.io"
baseurl: "/altieri-santarcangelo"
email: "petri.giovanni@gmail.com"

# shown top-left in the header
wordmark: "Rita &amp; Carlo"

nav:
  - title: "Photos"
    url: "/"
  - title: "About"
    url: "/about/"
