# Site settings
title: In memory of Rita Altieri and Carlo Santarcangelo
email: "petri.giovanni@gmail.com"
description: "Memorial gallery"
url: "https://lordgrilo.github.io"
baseurl: "/altieri-santarcangelo"
# facebook_username: ""
# twitter_username: ""
# instagram_username: ""
github_username:  "lordgrilo"
# deviantart_username: ""
# flickr_username: ""

# Owner/author information
owner:
  name:   Giovanni Petri
  avatar: avatar.png
  favicon: favicon.ico
  info: website in memory of Rita Altieri and Carlo Santarcangelo

# Internal nav
nav:
  - GALLERY: "/gallery/"
  - ABOUT: "/about/"


# Server
destination:      	 ./_site
port:             	 4000


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude: ["node_modules", "README.md"]

